"""empty message

Revision ID: e49baf73de4c
Revises: 
Create Date: 2020-01-16 05:52:40.789119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49baf73de4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('shop_id', table_name='carts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('shop_id', 'carts', ['shop_id'], unique=True)
    # ### end Alembic commands ###
